"""Enhanced admin_audit_logs table with new fields

Revision ID: 17f8c4081077
Revises: f1e0e735f45f
Create Date: 2026-02-11 12:35:25.485608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17f8c4081077'
down_revision: Union[str, None] = 'f1e0e735f45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_permissions_admin_id'), 'admin_permissions', ['admin_id'], unique=False)
    op.create_index('ix_admin_permissions_admin_permission', 'admin_permissions', ['admin_id', 'permission'], unique=False)
    op.create_index(op.f('ix_admin_permissions_permission'), 'admin_permissions', ['permission'], unique=False)
    op.add_column('admin_audit_logs', sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('admin_audit_logs', sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('admin_audit_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('admin_audit_logs', sa.Column('endpoint', sa.String(length=255), nullable=True))
    op.add_column('admin_audit_logs', sa.Column('method', sa.String(length=10), nullable=True))
    op.add_column('admin_audit_logs', sa.Column('status_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_audit_logs', 'status_code')
    op.drop_column('admin_audit_logs', 'method')
    op.drop_column('admin_audit_logs', 'endpoint')
    op.drop_column('admin_audit_logs', 'user_agent')
    op.drop_column('admin_audit_logs', 'after_state')
    op.drop_column('admin_audit_logs', 'before_state')
    op.drop_index(op.f('ix_admin_permissions_permission'), table_name='admin_permissions')
    op.drop_index('ix_admin_permissions_admin_permission', table_name='admin_permissions')
    op.drop_index(op.f('ix_admin_permissions_admin_id'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    # ### end Alembic commands ###
