"""Add password history tracking

Revision ID: 38750d9db325
Revises: 17f8c4081077
Create Date: 2026-02-11 20:46:31.491556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38750d9db325'
down_revision: Union[str, None] = '17f8c4081077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_created_at'), 'password_history', ['created_at'], unique=False)
    op.create_index('ix_password_history_user_created', 'password_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_index('ix_password_history_user_created', table_name='password_history')
    op.drop_index(op.f('ix_password_history_created_at'), table_name='password_history')
    op.drop_table('password_history')
    # ### end Alembic commands ###
