"""Add uniqueness constraint to events

Revision ID: 71544d844047
Revises: 37627b275b8f
Create Date: 2025-12-30 22:36:30.781501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71544d844047'
down_revision: Union[str, None] = '37627b275b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_event_title_date_loc', 'events', ['title', 'start_date', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_event_title_date_loc', 'events', type_='unique')
    # ### end Alembic commands ###
