"""add_privacy_columns_to_user_preferences

Revision ID: 90d5deb884d9
Revises: 202220f5bfb6
Create Date: 2026-02-16 01:52:44.862686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d5deb884d9'
down_revision: Union[str, None] = '202220f5bfb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('is_profile_public', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_preferences', sa.Column('allow_search_indexing', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_preferences', sa.Column('show_email', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_preferences', sa.Column('show_phone', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_preferences', sa.Column('attendance_visibility', sa.String(length=50), nullable=False, server_default='Friends & Connections'))
    op.add_column('user_preferences', sa.Column('past_events_visible', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_preferences', sa.Column('share_data_third_party', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_preferences', sa.Column('share_analytics', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'share_analytics')
    op.drop_column('user_preferences', 'share_data_third_party')
    op.drop_column('user_preferences', 'past_events_visible')
    op.drop_column('user_preferences', 'attendance_visibility')
    op.drop_column('user_preferences', 'show_phone')
    op.drop_column('user_preferences', 'show_email')
    op.drop_column('user_preferences', 'allow_search_indexing')
    op.drop_column('user_preferences', 'is_profile_public')
    # ### end Alembic commands ###
