"""add_is_archived_flag

Revision ID: 9983b2251532
Revises: 71544d844047
Create Date: 2026-01-02 00:01:55.634666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9983b2251532'
down_revision: Union[str, None] = '71544d844047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_events_is_archived'), 'events', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_is_archived'), table_name='events')
    op.drop_column('events', 'is_archived')
    # ### end Alembic commands ###
