"""add_refresh_token_id_and_tracking_fields_to_user_sessions_table

Revision ID: bde113c25c0d
Revises: 06ef887eef56
Create Date: 2026-02-10 23:49:15.732371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde113c25c0d'
down_revision: Union[str, None] = '06ef887eef56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token_id', sa.UUID(), nullable=True))
    op.add_column('user_sessions', sa.Column('device_info', sa.Text(), nullable=True))
    op.add_column('user_sessions', sa.Column('last_active_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_user_sessions_refresh_token_id'), 'user_sessions', ['refresh_token_id'], unique=False)
    op.create_foreign_key(None, 'user_sessions', 'refresh_tokens', ['refresh_token_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_refresh_token_id'), table_name='user_sessions')
    op.drop_column('user_sessions', 'last_active_at')
    op.drop_column('user_sessions', 'device_info')
    op.drop_column('user_sessions', 'refresh_token_id')
    # ### end Alembic commands ###
