"""add_avatar_url_to_userprofile_table

Revision ID: c2cabd9c15b1
Revises: bde113c25c0d
Create Date: 2026-02-11 01:52:19.882031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cabd9c15b1'
down_revision: Union[str, None] = 'bde113c25c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar_url')
    # ### end Alembic commands ###
