"""add_admin_user_management_models

Revision ID: e269506af1af
Revises: e6afaf94e117
Create Date: 2026-02-14 16:09:17.448317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e269506af1af'
down_revision: Union[str, None] = 'e6afaf94e117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notes_admin_id'), 'admin_notes', ['admin_id'], unique=False)
    op.create_index('ix_admin_notes_user_created', 'admin_notes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_notes_user_id'), 'admin_notes', ['user_id'], unique=False)
    op.create_table('impersonation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_impersonation_sessions_admin', 'impersonation_sessions', ['admin_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_admin_id'), 'impersonation_sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_session_token'), 'impersonation_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_impersonation_sessions_target_user_id'), 'impersonation_sessions', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impersonation_sessions_target_user_id'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_session_token'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_admin_id'), table_name='impersonation_sessions')
    op.drop_index('ix_impersonation_sessions_admin', table_name='impersonation_sessions')
    op.drop_table('impersonation_sessions')
    op.drop_index(op.f('ix_admin_notes_user_id'), table_name='admin_notes')
    op.drop_index('ix_admin_notes_user_created', table_name='admin_notes')
    op.drop_index(op.f('ix_admin_notes_admin_id'), table_name='admin_notes')
    op.drop_table('admin_notes')
    # ### end Alembic commands ###
